/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cricademy.views;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author arpannepal
 * LmuId 23048647
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHomeBackground = new javax.swing.JPanel();
        btnQuit = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnSearchPlayer1 = new javax.swing.JButton();
        btnPlayerInfo = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblHomeBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));

        pnlHomeBackground.setPreferredSize(new java.awt.Dimension(1000, 800));
        pnlHomeBackground.setSize(new java.awt.Dimension(1000, 800));
        pnlHomeBackground.setLayout(null);

        btnQuit.setBackground(new java.awt.Color(232, 95, 92));
        btnQuit.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        pnlHomeBackground.add(btnQuit);
        btnQuit.setBounds(20, 10, 180, 30);

        btnAdmin.setBackground(new java.awt.Color(124, 156, 171));
        btnAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        pnlHomeBackground.add(btnAdmin);
        btnAdmin.setBounds(710, 320, 220, 60);

        btnSearchPlayer1.setBackground(new java.awt.Color(124, 156, 171));
        btnSearchPlayer1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnSearchPlayer1.setText("Search Players");
        pnlHomeBackground.add(btnSearchPlayer1);
        btnSearchPlayer1.setBounds(70, 320, 230, 60);

        btnPlayerInfo.setBackground(new java.awt.Color(124, 156, 171));
        btnPlayerInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnPlayerInfo.setText("Player Info");
        btnPlayerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerInfoActionPerformed(evt);
            }
        });
        pnlHomeBackground.add(btnPlayerInfo);
        btnPlayerInfo.setBounds(390, 320, 220, 60);

        btnLogout.setBackground(new java.awt.Color(232, 203, 177));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlHomeBackground.add(btnLogout);
        btnLogout.setBounds(800, 10, 180, 30);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        lblTitle.setText("CRICADEMY");
        pnlHomeBackground.add(lblTitle);
        lblTitle.setBounds(330, 170, 340, 60);

        jTextArea2.setBackground(new java.awt.Color(232, 203, 177));
        jTextArea2.setColumns(25);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Welcome to Cricademy – Your Cricketing Journey Begins Here!\n\nLocated in Mulpani, Kathmandu, Cricademy is dedicated to nurturing cricketing talent and passion.With state-of-the-art facilities and experienced coaches, we offer personalized training for playersof all ages and skill levels. Our programs focus on building technical skills, mental resilience, \nand teamwork, shaping well-rounded athletes.\n\nAt Cricademy, we aim to inspire the next generation of cricket stars while fostering a deep love forthe game. Join our vibrant cricketing community and take your skills to the next level. Together, \nlet’s create unforgettable cricketing moments!");
        jTextArea2.setCaretColor(new java.awt.Color(232, 203, 177));
        jTextArea2.setSelectionColor(new java.awt.Color(232, 203, 177));
        jScrollPane2.setViewportView(jTextArea2);

        pnlHomeBackground.add(jScrollPane2);
        jScrollPane2.setBounds(370, 520, 590, 220);

        lblHomeBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cricademy/resource/homebackground.png"))); // NOI18N
        pnlHomeBackground.add(lblHomeBackgroundImage);
        lblHomeBackgroundImage.setBounds(0, 0, 1000, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHomeBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHomeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed

        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                null,"Are you sure you want to exit?","Confirm Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        // Check the user's response
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0); // Exit the program
        }
        
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int response1 = JOptionPane.showConfirmDialog(null,"Do you want to logout of the system?","Confirm Logout",
                JOptionPane.YES_NO_OPTION ,
                JOptionPane.QUESTION_MESSAGE);
        
        //check user response
        if (response1 == JOptionPane.YES_OPTION){
            Cricademy login = new Cricademy();
            login.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPlayerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerInfoActionPerformed
        // TODO add your handling code here:
        PlayerInfo playerInfo = new PlayerInfo();
        playerInfo.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnPlayerInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlayerInfo;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearchPlayer1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblHomeBackgroundImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHomeBackground;
    // End of variables declaration//GEN-END:variables
}
